### ISSUE TITLE
NoSuchKey: The specified key does not exist.

### ISSUE THREAD

**Issue by WVandergrift** [cloud-annotations/training#118]
I've been running through the Training an Object Detection Model tutorial and ran into an issue where training fails. The logs for the failed jobs show this error: `UnhandledPromiseRejectionWarning: NoSuchKey: The specified key does not exist.`

I noticed there's a [similar issue](https://github.com/IBM/ibm-cos-sdk-js/issues/26) in the [ibm-cos-sdk-js](https://github.com/IBM/ibm-cos-sdk-js) repo. The resolution for that issue was to use regional instead of cross-regional buckets. 

Unfortunately I've tried using both _Cross Region us-geo_ and _Regional us-south_ buckets to no avail.

Here's my current configuration:
- Machine Learning Instance in the Dallas location (https://us-south.ml.cloud.ibm.com)
- Multiple buckets tried on both us-geo and us-south

config.yaml file:
```
buckets:
  training: firearm-detection-storage-bucket
trainingParams:
  gpu: k80
  steps: '500'
name: firearm-detection
```

I've tried running the cli on Windows 10 with Node 10.16.3 and Ubuntu 19.04 with Node 10.13.0.

Any idea what could be causing this issue?
