### ISSUE TITLE
add support for system wide credentials

### ISSUE THREAD

**Issue by bourdakos1** [cloud-annotations/training#42]
Something like:
```
cacli init [--profile=other-user]
```
Would store credentials to `~/.cacli/credentials`:
```
[default]
instance_id: ***
username: ***
password: ***
url: ***
access_key_id: ***
secret_access_key: ***
region: us-geo
[other-user]
instance_id: ***
username: ***
password: ***
url: ***
access_key_id: ***
secret_access_key: ***
region: us-geo
```
and then in `config.yaml`:
```yaml
name: my-training-bucket
buckets:
  training: my-training-bucket
  output: my-output-bucket
trainingParams:
  gpu: v100
  steps: 500
```

Side issue, we should add the ability to have more granular control over bucket regions: (not necessarily in UI, but the config should understand this option) #44 
```yaml
name: my-training-bucket
buckets:
  training: my-training-bucket
  output: my-output-bucket
  region: 
    training: us-south
    output: us-geo
trainingParams:
  gpu: v100
  steps: 500
```
