### ISSUE TITLE
More granular control over training

### ISSUE THREAD

**Issue by bourdakos1** [cloud-annotations/training#44]
We should add the ability to have more granular control over training:
current:
```yaml
name: my-project
buckets:
  training: my-training-bucket
  output: my-output-bucket
trainingParams:
  gpu: v100
  steps: 500
```

plan:
```yaml
name: untitled-project
buckets:
  training: my-training-bucket
  output: my-output-bucket
bucketParams:
  output:
    accessKeyId: '***' # taken from `~/.cacli`
    secretAccessKey: '***' # taken from `~/.cacli`
    # Only specify `endpointUrl` or `region`
    endpointUrl: https://s3-api.us-geo.objectstorage.softlayer.net
    region: us-geo # taken from `~/.cacli`
trainingParams:
  gpu: k80
  steps: 500
  framework:
    name: tensorflow
    version: '1.13'
  runtimes:
    name: python
    version: '3.5'
  model:
    type: object-detection # Defaults to object detection if annotation type `localization`
    config: https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_coco.config
    outputs: # If specified, only exports what is listed. Otherwise exports all.
      - coreml
      - tfjs
      - tflite
```
required:
```yaml
buckets:
  training: my-training-bucket
```
